# Generated by Django 4.0 on 2022-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
