# Generated by Django 4.0 on 2021-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='govtproof',
            name='id_type',
            field=models.CharField(choices=[('Aadhar', 'Aadhar'), ('Pan', 'Pan'), ('DL', 'DL')], default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
