# Generated by Django 4.0.5 on 2022-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_name',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.Ed', 'B.Ed'), ('BA', 'B.A'), ('M.Tech', 'M.Tech'), ('M.Sc', 'M.Sc'), ('M.A', 'M.A'), ('MBA', 'MBA'), ('Intermediate', 'Intermediate'), ('SSC', 'SSC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('ElderBrother', 'Elder_Borther'), ('YoungerBrother', 'Younger_Brother'), ('ElderSister', 'Younger_Sister'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=100),
        ),
    ]
